package com.ista.dmi.pcs.billing.domain;

/**
 * Definition for violation message.
 */

public final class ViolationMessage {

  /**
   * Used to determine dynamically the parameter index for contract management parameters.
   */
  public static final String CM_PARAM_PREFIX = "CM_PARAM_";

  private ViolationMessage() {
  }

  /**
   * Key for the violation message.
   */
  public enum Key {
    HEAT_COST_ALLOCATOR_WITH_INCOMPLETE_SCALE,
    METERING_POINT_WITHOUT_DEVICES,
    USAGE_UNIT_WITH_VOLUMETERS_WITH_UNDEFINED_DISPLAY_UNITS,
    USAGE_UNIT_WITHOUT_METERING_POINTS,
    MISSING_DISTRIBUTION_VALUE,
    INVALID_DISTRIBUTION_VALUE,
    MISSING_ASSIGNMENT_FROM_INTERIM_READING_FEE_TO_SERVICE_RECIPIENT,
    MISSING_ASSIGNMENT_FROM_REREADING_FEE_TO_SERVICE_RECIPIENT,
    INTERIM_READING_WITHOUT_USER_CHANGE,
    DISTRIBUTION_FOR_USER_NOT_POSSIBLE,
    ERROR_IN_DEVICE_OR_METERING_POINT_CONSUMPTION,
    METERING_POINT_WITHOUT_SCALE_INFORMATION,

    CONSUMPTION_WITHOUT_METERING_VALUE_START,
    CONSUMPTION_WITHOUT_METERING_VALUE_END,
    CONSUMPTION_WITHOUT_METERING_VALUE_START_AND_END,
    CONSUMPTION_WITH_METERING_VALUE_START_GREATER_THAN_DOUBLE_SCALE,
    CONSUMPTION_WITH_METERING_VALUE_END_GREATER_THAN_DOUBLE_SCALE,
    CONSUMPTION_WITH_METERING_VALUE_START_AND_END_GREATER_THAN_DOUBLE_SCALE,
    CONSUMPTION_WITH_METERING_VALUE_START_GREATER_THAN_FORTY,
    CONSUMPTION_WITH_METERING_VALUE_END_GREATER_THAN_FORTY,
    CONSUMPTION_WITH_METERING_VALUE_START_AND_END_GREATER_THAN_FORTY,
    CONSUMPTION_WITH_METERING_VALUE_START_GREATER_THAN_HUNDRED,
    CONSUMPTION_WITH_METERING_VALUE_END_GREATER_THAN_HUNDRED,
    CONSUMPTION_WITH_METERING_VALUE_START_AND_END_GREATER_THAN_HUNDRED,
    UNESTIMATED_VALUE_FOR_NON_EQUIPPED_METERING_POINT,

    CHECK_OPEN_SERVICE_ORDERS_EXIST,
    CHECK_FOR_INVOICING_RELATED_INFORMATION,
    CHECK_CUSTOMER_DATA_PLAUSIBILITY,
    REVIEW_BILLING,
    REVIEW_KOLI_NULI,
    REVIEW_SERVICE_INVOICE,
    PROVIDE_NO_KOLI_NULI,
    CHECK_CONSUMPTIONS_PLAUSIBILITY,
    CHECK_DELAY_REASON_OF_SERVICE_INVOICE_NUMBERS,
    CHECK_DELAY_REASON_OF_FINAL_INVOICE_NUMBERS,
    CM_LOCK_ERROR_002,
    CM_LOCK_ERROR_026,
    CM_LOCK_ERROR_064,
    CM_LOCK_ERROR_103,
    CM_INTERFACE_ERROR_018,
    CM_INTERFACE_ERROR_067,
    CM_INTERFACE_ERROR_251,
    CM_INTERFACE_INFORMATION_074,
    CM_INTERFACE_INFORMATION_254,

    INVALID_ASSIGNMENT_RE_READING_FEE_TO_COMMON_USAGE_UNIT,
    INVALID_ASSIGNMENT_INTERIM_READING_FEE_TO_COMMON_USAGE_UNIT,

    CONTRACT_GENERAL_MESSAGE,
    CONTRACT_ORDER_GENERAL_MESSAGE,

    PROPERTY_TEXT_EXISTS_BEFORE_CONSUMPTION_CALCULATION,
    PROPERTY_TEXT_EXISTS_AFTER_CONSUMPTION_CALCULATION,
    PROPERTY_TEXT_EXISTS_AFTER_COST_ALLOCATION
  }

  /**
   * Possible attribute names for a violation message.
   */
  public enum Attribute {
    DEVICE_UUID,
    USAGE_UNIT_UUID,
    METERING_POINT_UUID,
    SERVICE_RECIPIENT_UUID,
    INNER_FEE_UUID,
    PPS_ORDER_NUMBER,
    ALLOCATION_KEY,
    SERVICE_TYPE,
    SCALE,
    START_DATE,
    END_DATE,
    INVOICE_NUMBER,
    INVOICE_ATTACHMENT_NUMBER_LIST,
    /**
     * Consider that the following literals dynamically referenced via CM_PARAM_PREFIX constant.
     */
    CM_PARAM_1,
    CM_PARAM_2,
    CM_PARAM_3,
    CM_PARAM_4,

    SAP_NUMBER,
    CONTENT
  }

}

